language: node_js
node_js:
  - '10'

before_deploy:
  - BASE_PATH=/react-swipe-props yarn build-demo
  - cp dist/index.html dist/404.html

deploy:
  provider: pages
  local-dir: dist
  skip-cleanup: true
  github-token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
